# ---------- base ----------
FROM node:20.5.0-alpine AS base
WORKDIR /repo
RUN corepack enable

# ---------- builder ----------
FROM base AS builder
WORKDIR /repo

# Copy full repo for dependency graph
COPY . .

# Install deps needed for turbo prune
RUN pnpm install --frozen-lockfile

# Builds @msgbits/api and workspace dependencies(...) it needs
RUN pnpm --filter=@msgbits/api... build

# Prune only api app
RUN pnpm exec turbo prune --scope=@msgbits/api --docker

# Deploy creates fat node_modules with all dependencies
RUN pnpm --filter=@msgbits/api deploy --prod --legacy /prod/api

COPY apps/api/public /prod/api/public

# ---------- production ----------
FROM node:20.5.0-alpine AS production

WORKDIR /app

# Create non-root user
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

# Copy everything from /prod/api (now has correct structure)
COPY --from=builder --chown=nodejs:nodejs /prod/api ./

# Environment variables
ENV NODE_ENV=production \
    NODE_CONFIG_DIR=/app/config \
    REDIS_HOST=redis \
    REDIS_PORT=6379

USER nodejs

EXPOSE 8080

CMD ["node", "dist/index.js"]
# Stops container from exiting
#CMD ["tail", "-f", "/dev/null"] 

